# Generated by Django 2.2.7 on 2019-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('price', models.IntegerField(max_length=12)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
